// import { modelPrefixName } from "../models/contacts";

export const MEETING_INFO_MODIFY = "MEETING_INFO_MODIFY";
export const MEETING_MEMBERS_ADD = "MEETING_MEMBERS_ADD";
export const MEETING_MEMBERS_DELETE = "MEETING_MEMBERS_DELETE";
export const MEETING_SUMMARIES_PUBLISH = "MEETING_SUMMARIES_PUBLISH";
export const MEETINGS_FINISH = "MEETINGS_FINISH";
export const MEETING_MEMBERS_FEEDBACK = "MEETING_MEMBERS_FEEDBACK";
